# version: "3.8"

services:
  careernest-api1:
    build: .
    container_name: careernest-api1
    networks:
      - app-network
    restart: always
    environment:
      - PORT=5001
    env_file:
      - ./.env
    volumes:
      - ./public:/app/public

  careernest-api2:
    build: .
    container_name: careernest-api2
    networks:
      - app-network
    restart: always
    environment:
      - PORT=5002
    env_file:
      - ./.env
    volumes:
      - ./public:/app/public

  careernest-api3:
    build: .
    container_name: careernest-api3
    networks:
      - app-network
    restart: always
    environment:
      - PORT=5003
    env_file:
      - ./.env
    volumes:
      - ./public:/app/public

  nginx:
    build: ./nginx
    container_name: nginx-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - /etc/letsencrypt:/etc/letsencrypt
      # - /var/www:/var/www
    depends_on:
      - careernest-api1
      - careernest-api2
      - careernest-api3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge